FrederikMoestrup/ALF4HUB

Backend/src/main/java/dat/config/HibernateConfig.java
Backend/src/main/java/dat/daos/BlogPostDAO.java
Backend/src/main/java/dat/dtos/BlogPostDTO.java
Backend/src/main/java/dat/entities/BlogPost.java
Backend/src/main/java/dat/enums/BlogPostStatus.java
Backend/src/test/java/US3/dat/daos/BlogPostDAOTest.java
Backend/src/test/java/dat/daos/BlogPostDAOTest.java

- Created BlogPostDAO with methods for save, getById, getAll and getAllWithOnlyContentPreview
- Added BlogPostDAOTest with tests for persistence and retrieval
- Verified database interaction using JPA and test database

feat: Implement BlogPostDAO and corresponding DAO tests

---

Backend/src/main/java/dat/controllers/TeamController.java
Backend/src/main/java/dat/daos/TeamDAO.java
Backend/src/main/java/dat/routes/TeamRoute.java

in TeamDAO, TeamController and TeamRoutes

added Add player

---

Backend/src/main/java/dat/controllers/BlogController.java
Backend/src/main/java/dat/routes/BlogRoute.java

* Created routes depending on available dao methods
* Added roles to each endpoint
* Created empty Controller class to allow for better git flow (Controller logic coming next request)

feat: Implement route setup, with Security roles 

---

Backend/src/main/java/dat/controllers/BlogController.java
Backend/src/main/java/dat/daos/BlogPostDAO.java
Backend/src/main/java/dat/routes/BlogRoute.java
Backend/src/main/java/dat/routes/Routes.java

* Created controller methods that connects DAO method's to Route's
* Added Exception handling for various exceptions that might occur 
*  Added routes to the routes layout

feat: Implement controller setup 

---

Backend/pom.xml
Backend/src/main/java/dat/controllers/BlogController.java
Backend/src/main/java/dat/daos/BlogPostDAO.java
Backend/src/main/java/dat/routes/BlogRoute.java
Backend/src/main/java/dat/routes/Routes.java
Backend/src/test/java/US3/dat/controllers/BlogControllerTest.java

* Added testing for the controller methods
* verified the exception handling is working as intended

feat: Implement Controller Testing

---

Frontend/src/main.jsx
Frontend/src/pages/BlogPostFrontPage.jsx

- Made a pages folder and created BlogPostFrontPage in that folder
- Made the UI for that page but no functionality yet
- Added BlogPostFrontPage to main.jsx so I was able to see the layout of the page

feat: Implement BlogPost front page design

---

Frontend/src/main.jsx
Frontend/src/pages/BlogPostFrontPage.jsx
Frontend/src/pages/CreateBlogPost.jsx

- Added a CreateBlogPost page and made the UI for that page but no functionality yet
- Put in a form to create a new blogpost where you have to fill out title and content
- Added CreateBlogPost to main.jsx so I was able to see the layout of the page

feat: Add create new blogpost design

---

Backend/src/main/java/dat/daos/PlayerAccountDAO.java
Backend/src/main/java/dat/daos/TournamentDAO.java
Backend/src/main/java/dat/dtos/PlayerAccountDTO.java
Backend/src/main/java/dat/dtos/TeamDTO.java
Backend/src/main/java/dat/dtos/UserDTO.java
Backend/src/main/java/dat/entities/User.java
Backend/src/main/java/dat/security/controllers/SecurityController.java
Backend/src/main/java/dat/security/daos/ISecurityDAO.java
Backend/src/main/java/dat/security/daos/SecurityDAO.java
Backend/src/main/java/dat/security/routes/SecurityRoutes.java
Backend/src/main/resources/http/dev.http

Fixed user/security: register, login, addrole. dev.http testing done on basic dao methods for PlayerAccount, Team, Tournament. DTO constructors changed to prevent stack.

Techleadfixing

---

Backend/src/main/java/dat/Main.java
Backend/src/main/java/dat/controllers/WordCheckController.java
Backend/src/main/java/dat/routes/Routes.java
Backend/src/main/java/dat/routes/WordCheckRoute.java
Backend/src/main/java/dat/services/OffensiveWordsService.java
Backend/src/main/resources/test/java/OffensiveWordsServiceTest.java

En liste der håndteres i Backend med stødende ord

Mk developer h

---

.idea/.gitignore
.idea/ALF4HUB.iml
.idea/compiler.xml
.idea/encodings.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
Backend/pom.xml
Backend/src/main/java/dat/controllers/UserController.java
Backend/src/main/java/dat/daos/UserDAO.java
Backend/src/main/java/dat/dtos/UserDTO.java
Backend/src/main/java/dat/entities/User.java
Backend/src/main/java/dat/routes/UserRoute.java
Backend/src/test/java/UserStrikeStepDefinitions.java
Backend/src/test/java/resources.features/AddStrikeToUser.feature

Add strike to user

---

.idea/.gitignore
.idea/compiler.xml
.idea/encodings.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/workspace.xml
Frontend/src/pages/EditBlogPost.jsx

Just needs to be connected to an edit button

EditBlogPost component created. 

---

Backend/src/main/java/dat/controllers/BlogController.java
Backend/src/main/java/dat/daos/BlogPostDAO.java
Backend/src/main/java/dat/enums/BlogPostStatus.java
Backend/src/main/java/dat/routes/BlogRoute.java
Backend/src/main/java/dat/service/BlogPostService.java
Backend/src/test/java/US3/dat/controllers/BlogControllerTest.java
Backend/src/test/java/US3/dat/daos/BlogPostDAOTest.java
Backend/src/test/java/US3/steps/BlogPostSteps.java

Feat: Added routing, controller and service logic for creating a blog post as a draft
Main:
- Added a new route for creating a draft
- Added a method in BlogController to handle the routing and to send to service class
- Added a method to our service class to check for empty content before sending to DAO
Additional:
- Changes to test class to match the overall changes to our methods, so they pass
- Removed comments and unused imports
- Changed some logic for finding existing user in dao methods

Team F draft error and routing

---

Backend/src/main/java/dat/config/HibernateConfig.java
Backend/src/main/java/dat/controllers/PlayerAccountController.java
Backend/src/main/java/dat/controllers/TeamController.java
Backend/src/main/java/dat/controllers/TournamentController.java
Backend/src/main/java/dat/controllers/TournamentTeamController.java
Backend/src/main/java/dat/daos/PlayerAccountDAO.java
Backend/src/main/java/dat/daos/TeamDAO.java
Backend/src/main/java/dat/daos/TournamentDAO.java
Backend/src/main/java/dat/daos/TournamentTeamDAO.java
Backend/src/main/java/dat/dtos/PlayerAccountDTO.java
Backend/src/main/java/dat/dtos/TeamDTO.java
Backend/src/main/java/dat/dtos/TournamentDTO.java
Backend/src/main/java/dat/dtos/TournamentTeamDTO.java
Backend/src/main/java/dat/dtos/UserDTO.java
Backend/src/main/java/dat/entities/PlayerAccount.java
Backend/src/main/java/dat/entities/Team.java
Backend/src/main/java/dat/entities/Tournament.java
Backend/src/main/java/dat/entities/TournamentTeam.java
Backend/src/main/java/dat/entities/User.java
Backend/src/main/java/dat/enums/TournamentStatus.java
Backend/src/main/java/dat/routes/PlayerAccountRoute.java
Backend/src/main/java/dat/routes/Routes.java
Backend/src/main/java/dat/routes/TeamRoute.java
Backend/src/main/java/dat/routes/TournamentRoute.java
Backend/src/main/java/dat/routes/TournamentTeamRoute.java
Backend/src/main/resources/http/dev.http

Entity, DTO, DAO, controller and routes added for TournamentTeam. Some of the previous entities, DTOs, DAOs, controllers have been changed. This includes some of the relations between entities.

TournamentTeams added

---

Frontend/src/App.jsx
Frontend/src/components/PopUpMessage.jsx
Frontend/src/pages/BlogPostFrontPage.jsx
Frontend/src/pages/CreateBlogPost.jsx
Frontend/src/styles/blogPostFrontPageStyles.js
Frontend/src/styles/createBlogPostStyles.js
Frontend/src/styles/popUpMessageStyles.js

Feat: Created component for error or success message when saving blogpost as draft or published
- Created pop up modal component to show a message
- Renamed frontend route path for blogpost frontpage
- Refactored styled component into their own js files 
- Handles backend API call for both creating blogpost as draft and as published work

Team f frontend draft error handling

---

Frontend/src/pages/BlogPostFrontPage.jsx

With confirmation when clicked

Added delete button

---

Frontend/src/main.jsx
Frontend/src/pages/blog/CreateBlogPost.jsx
Frontend/src/pages/blog/Drafts.jsx
Frontend/src/pages/blog/styles/createBlogPostStyles.js

Refactor: Updated existing page for creating a blog post to match the new Figma design
- Refactored old JSX structure to match the new design layout
- Updated CSS/styled-components to reflect new style
- Ensured responsiveness for big and small screens
Other:
- Removed reference in Draft page to the stylesheet for creating a blog post
- fixed a missing export error in main

Dev team f frontend styling create blogpost

---

Frontend/src/index.css
Frontend/src/pages/blog/Drafts.jsx
Frontend/src/pages/blog/styles/draftsPageStyles.js

style: add draftsPageStyles.js for Drafts page

style: add dedicated styles for Drafts page

---

Backend/src/test/java/US20/ReadDeletedBlogPost.java
Backend/src/test/java/US20/deleted_blogpost.feature

Made a simple cucumber test for AC 2. Cant run since the other tests in the project are broken. But i have tested it in another project, and it works and test passes.

Cucumber Acceptance crit 2

---

Backend/src/main/java/dat/controllers/NotificationController.java
Backend/src/main/java/dat/daos/NotificationDAO.java
Backend/src/main/java/dat/daos/UserDAO.java
Backend/src/main/java/dat/dtos/NotificationDTO.java
Backend/src/main/java/dat/entities/Notification.java
Backend/src/main/java/dat/routes/NotificationRoute.java
Backend/src/main/java/dat/routes/Routes.java
Backend/src/main/resources/http/dev.http

Nu har jeg taget Umair arbejde med og udeladt alt andet. Dette dækker de task der gør at en bruger når han logger ind kan se om han har nye notifications og får en klokke frem som leder ham til alle hans notifications. På den pagge kan han klikke på hver enkelt og derudover vil der være en knap som sørger for at alle notifications bliver markeret som læst.

Team h backend lars - userstory 15

---

Frontend/src/pages/blog/CreateBlogPost.jsx
Frontend/src/pages/blog/Drafts.jsx
Frontend/src/pages/blog/ForumPage.jsx
Frontend/src/pages/blog/styles/createBlogPostStyles.js
Frontend/src/pages/blog/styles/draftsPageStyles.js

Fix: Creating blogpost now working with only a logged in user
- Fixed call to api with the correct credentials 
- Smaller adjustments to error handling 
Other:
- Removed frontend styling from Draft Page to follow figma design
- Adjustet styling for Create Post Page to be more responsive

Dev team f fix api call with correct user id

---

Backend/src/main/java/dat/config/HibernateConfig.java
Backend/src/main/java/dat/controllers/NotificationController.java
Backend/src/main/java/dat/daos/NotificationDAO.java
Backend/src/main/java/dat/dtos/NotificationDTO.java
Backend/src/main/java/dat/entities/Notification.java
Backend/src/main/java/dat/enums/NotificationType.java
Backend/src/main/java/dat/routes/NotificationRoute.java
Backend/src/main/java/dat/security/tokenSecurity/TokenSecurity.java
Backend/src/main/resources/http/dev.http

Dev team h sprint3 merged umair b4

---

Backend/src/main/java/dat/populator/Populator.java
Backend/src/main/java/dat/populator/generator/BlogPostGenerator.java
Frontend/src/pages/blog/BlogPostFrontPage.jsx
Frontend/src/pages/blog/ReadBlogPost.jsx
Frontend/src/pages/blog/styles/blogPostFrontPageStyles.js

En blogpost generator lavet og integreret i populator. Og navigation til en ny side når man clicker fra BlogPostFrontPage.jsx til ReadBlogPost.jsx hvor man ville kunne se den fulde blogpost.

BlogPostGenerator og Fuld side med blogpost
